version: "3"
services:
  backend:
    build: backend
    restart: always
    container_name: fileflow_backend
    depends_on:
      - fileflow_db
    ports:
      - "8295:8295"
    env_file:
      - .env
    volumes:
      - ff-data:/data
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.driverClassName": "org.postgresql.Driver",
        "spring.datasource.url"  : "$SPRING_DATASOURCE_URL",
        "app.jwt.secret": "$JWT_SECRET_KEY",
        "spring.datasource.username" : "$SPRING_DATASOURCE_USERNAME",
        "spring.datasource.password" : "$SPRING_DATASOURCE_PASSWORD",
        "server.port": $SERVER_PORT,
        "spring.jpa.hibernate.ddl-auto" : "update"}'
  fileflow_db:
    container_name: fileflow_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ff_user
      POSTGRES_PASSWORD: secretpassword123
      POSTGRES_DB: fileflow
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local
  ff-data:
